apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: hiops
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: iemdb-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: iemdb-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iemdb-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iemdb-mysql
  template:
    metadata:
      labels:
        app: iemdb-mysql
    spec:
      containers:
        - image: quay.io/sina/mysql:8.0
          name: iemdb-mysql
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      restartPolicy: Always